import { collection, key } from "@dal-go/dalgo";
import { describe, expect, it, vi } from "vitest";
import { CouchbaseCasMismatchError, CouchbaseDataApiDatabase, CouchbaseDataApiError } from "../src/index.js";

function response(status: number, value?: unknown, headers: Record<string, string> = {}): Response { return new Response(value === undefined ? undefined : JSON.stringify(value), { status, headers }); }
function setup() { const fetch = vi.fn<typeof globalThis.fetch>(); const database = new CouchbaseDataApiDatabase({ endpoint: "https://cluster.data.cloud.couchbase.com", authorization: () => "Bearer opaque", collections: { items: { bucket: "app", scope: "_default", collection: "items" } }, fetch }); return { database, fetch }; }
describe("CouchbaseDataApiDatabase", () => {
  it("uses the documented Data API path, opaque authorization, and envelope", async () => { const { database, fetch } = setup(); fetch.mockResolvedValueOnce(response(200, { __dalgo_id: "milk", data: { done: false } }, { etag: "cas" })); await expect(database.get<{ done: boolean }>(key("items", "milk"))).resolves.toEqual({ key: key("items", "milk"), exists: true, data: { done: false }, metadata: { etag: "cas" } }); expect(fetch).toHaveBeenCalledWith("https://cluster.data.cloud.couchbase.com/v1/buckets/app/scopes/_default/collections/items/documents/Im1pbGsi", expect.objectContaining({ method: "GET", headers: expect.objectContaining({ authorization: "Bearer opaque" }) })); });
  it("maps insert conflict and CAS precondition conflicts", async () => { const { database, fetch } = setup(); fetch.mockResolvedValueOnce(response(409)); await expect(database.insert(key("items", "milk"), { done: false })).rejects.toMatchObject({ name: "AlreadyExistsError" }); fetch.mockResolvedValueOnce(response(409)); await expect(database.setIfMatch(key("items", "milk"), { done: true }, "cas")).rejects.toBeInstanceOf(CouchbaseCasMismatchError); expect(fetch.mock.calls[1]?.[1]).toMatchObject({ headers: expect.objectContaining({ "if-match": "cas" }) }); });
  it("uses parameterized Query Service passthrough and rejects body leakage", async () => { const { database, fetch } = setup(); fetch.mockResolvedValueOnce(response(200, { results: [{ __dalgo_id: "milk", data: { done: false } }], status: "success" })); const items = collection<{ done: boolean }>("items"); await expect(database.query(items.query().where("done", "==", false).limit(5).build())).resolves.toMatchObject({ records: [{ data: { done: false } }] }); expect(fetch.mock.calls[0]?.[0]).toBe("https://cluster.data.cloud.couchbase.com/_p/query/query/service"); expect(JSON.parse(fetch.mock.calls[0]?.[1]?.body as string)).toMatchObject({ "$p0": false }); fetch.mockResolvedValueOnce(response(500, { message: "secret server detail" })); await expect(database.get(key("items", "a"))).rejects.toEqual(new CouchbaseDataApiError("get", 500)); });
  it("rejects unsafe identifiers and lossy JSON before making a request", async () => { const fetch = vi.fn<typeof globalThis.fetch>(); const database = new CouchbaseDataApiDatabase({ endpoint: "https://cluster.data.cloud.couchbase.com", authorization: () => "Bearer opaque", collections: { items: { bucket: "app` UNION SELECT", scope: "_default", collection: "items" } }, fetch }); await expect(database.get(key("items", "a"))).rejects.toThrow("bucket"); const safe = setup(); await expect(safe.database.set(key("items", "a"), { impossible: Number.NaN })).rejects.toThrow("finite"); await expect(safe.database.set(key("items", "a"), { big: 1n })).rejects.toThrow("bigint"); expect(safe.fetch).not.toHaveBeenCalled(); });
  it("rejects malformed point identity and SQL++ envelopes", async () => { const { database, fetch } = setup(); fetch.mockResolvedValueOnce(response(200, { __dalgo_id: "other", data: {} })); await expect(database.get(key("items", "wanted"))).rejects.toThrow("envelope"); fetch.mockResolvedValueOnce(response(200, { results: [], status: "errors", errors: [{ msg: "secret" }] })); const items = collection<{ done: boolean }>("items"); await expect(database.query(items.query().build())).rejects.toThrow("SQL"); });
  it("sets redirect:error and rejects invalid safe-integer document IDs", async () => { const { database, fetch } = setup(); fetch.mockResolvedValueOnce(response(404)); await database.get(key("items", "a")); expect(fetch.mock.calls[0]?.[1]).toMatchObject({ redirect: "error" }); await expect(database.get(key("items", 1.5))).rejects.toThrow("safe integers"); expect(fetch).toHaveBeenCalledTimes(1); });
  it("rejects runtime-injected document-id operators and CRLF ETags before fetch", async () => { const { database, fetch } = setup(); const items = collection<{ done: boolean }>("items"); const query = items.query().where("__name__", "==", "a").build(); const poisoned = { ...query, filters: [{ field: "__name__", operator: "= 1; DELETE" as never, value: "a" }] }; await expect(database.query(poisoned)).rejects.toThrow("operator"); await expect(database.setIfMatch(key("items", "a"), { done: true }, "cas\r\nInjected: yes")).rejects.toThrow("CR or LF"); expect(fetch).not.toHaveBeenCalled(); });
});
