import { AlreadyExistsError, Key, UnsupportedError, identityCodec, type Codec, type Database, type ExistingRecord, type QueryPage, type RecordSnapshot, type StructuredQuery, type UpdateData } from "@dal-go/dalgo";

export type CouchbaseFetch = typeof globalThis.fetch;
export type CouchbaseAuthorizationProvider = () => string | Promise<string>;
/** Names use the intentionally strict SQL++ identifier grammar. */
export interface CouchbaseCollectionTarget { readonly bucket: string; readonly scope: string; readonly collection: string; }
export interface CouchbaseDataApiOptions {
  readonly endpoint: string;
  readonly authorization: CouchbaseAuthorizationProvider;
  readonly collections: Readonly<Record<string, CouchbaseCollectionTarget>> | ((collectionPath: string) => CouchbaseCollectionTarget);
  readonly timeoutMs?: number; readonly maxRequestBytes?: number; readonly maxResponseBytes?: number;
  readonly maxGetManyKeys?: number; readonly maxParallelReads?: number; readonly maxQueryLimit?: number; readonly maxSqlBytes?: number;
  readonly fetch?: CouchbaseFetch;
}
interface Options { endpoint: string; authorization: CouchbaseAuthorizationProvider; collections: CouchbaseDataApiOptions["collections"]; timeoutMs: number; maxRequestBytes: number; maxResponseBytes: number; maxGetManyKeys: number; maxParallelReads: number; maxQueryLimit: number; maxSqlBytes: number; fetch: CouchbaseFetch; }
interface Envelope { readonly __dalgo_id: string | number; readonly data: unknown; }
export class CouchbaseDataApiError extends Error { public constructor(public readonly operation: string, public readonly status: number) { super(`Couchbase Data API ${operation} failed with HTTP ${status}`); this.name = "CouchbaseDataApiError"; } }
export class CouchbaseCasMismatchError extends Error { public constructor() { super("Couchbase Data API CAS precondition failed"); this.name = "CouchbaseCasMismatchError"; } }
export class CouchbaseAuthorizationError extends Error { public constructor() { super("Couchbase Data API authorization provider failed"); this.name = "CouchbaseAuthorizationError"; } }
const encoder = new TextEncoder();
function bound(value: number | undefined, fallback: number, name: string, maximum: number): number { const result = value ?? fallback; if (!Number.isSafeInteger(result) || result < 1 || result > maximum) throw new TypeError(`${name} must be a safe integer from 1 to ${maximum}`); return result; }
function text(value: string, name: string): string { if (value.trim().length === 0) throw new TypeError(`${name} must not be empty`); return value; }
function validPart(value: string, name: string): string { text(value, name); if (!/^[A-Za-z_][A-Za-z0-9_]*$/u.test(value)) throw new TypeError(`${name} must use ASCII letters, digits, and underscore and begin with a letter or underscore`); return value; }
function resolve(input: CouchbaseDataApiOptions): Options { const url = new URL(input.endpoint); const loopback = url.hostname === "localhost" || url.hostname === "127.0.0.1" || url.hostname === "[::1]"; if (url.protocol !== "https:" && !(url.protocol === "http:" && loopback) || url.username || url.password || url.pathname !== "/" || url.search || url.hash) throw new TypeError("endpoint must be an HTTPS origin (HTTP only for loopback) with no path, credentials, query, or fragment"); if (typeof input.authorization !== "function") throw new TypeError("authorization must be a function"); return { endpoint: url.origin, authorization: input.authorization, collections: input.collections, timeoutMs: bound(input.timeoutMs, 15_000, "timeoutMs", 120_000), maxRequestBytes: bound(input.maxRequestBytes, 1_048_576, "maxRequestBytes", 16_777_216), maxResponseBytes: bound(input.maxResponseBytes, 1_048_576, "maxResponseBytes", 16_777_216), maxGetManyKeys: bound(input.maxGetManyKeys, 100, "maxGetManyKeys", 1000), maxParallelReads: bound(input.maxParallelReads, 8, "maxParallelReads", 100), maxQueryLimit: bound(input.maxQueryLimit, 100, "maxQueryLimit", 1000), maxSqlBytes: bound(input.maxSqlBytes, 131_072, "maxSqlBytes", 1_048_576), fetch: input.fetch ?? globalThis.fetch }; }
function keyId(value: unknown): asserts value is string | number { if (typeof value !== "string" && !(typeof value === "number" && Number.isSafeInteger(value) && !Object.is(value, -0))) throw new TypeError("DALgo key IDs must be strings or safe integers, excluding -0"); }
function storageKey(value: string | number): string { keyId(value); const bytes = encoder.encode(JSON.stringify(value)); let binary = ""; for (const byte of bytes) binary += String.fromCharCode(byte); return btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); }
function object(value: unknown): asserts value is Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new TypeError("Couchbase DALgo records must encode to a non-null object"); }
function jsonValue(value: unknown, seen = new WeakSet()): void { if (value === null || typeof value === "string" || typeof value === "boolean") return; if (typeof value === "number") { if (!Number.isFinite(value)) throw new TypeError("Couchbase JSON values must contain finite numbers"); return; } if (Array.isArray(value)) { if (seen.has(value)) throw new TypeError("Couchbase JSON values must not be cyclic"); seen.add(value); value.forEach((entry) => { jsonValue(entry, seen); }); seen.delete(value); return; } if (typeof value === "object") { const record = value as Record<string, unknown>; const prototype = Object.getPrototypeOf(record); if (prototype !== Object.prototype && prototype !== null) throw new TypeError("Couchbase JSON values must use plain records and arrays"); if (seen.has(record)) throw new TypeError("Couchbase JSON values must not be cyclic"); seen.add(record); for (const name of Object.keys(record)) jsonValue(record[name], seen); seen.delete(record); return; } throw new TypeError("Couchbase JSON values must not contain undefined, functions, symbols, or bigint"); }
async function body(response: Response, maximum: number): Promise<string> { const length = response.headers.get("content-length"); if (length !== null && (!Number.isSafeInteger(Number(length)) || Number(length) < 0 || Number(length) > maximum)) { await response.body?.cancel(); throw new RangeError("Couchbase response exceeds maxResponseBytes"); } if (!response.body) return ""; const reader = response.body.getReader(); const chunks: Uint8Array[] = []; let total = 0; try { for (;;) { const next = await reader.read(); if (next.done) break; total += next.value.byteLength; if (total > maximum) { await reader.cancel(); throw new RangeError("Couchbase response exceeds maxResponseBytes"); } chunks.push(next.value); } } finally { reader.releaseLock(); } const bytes = new Uint8Array(total); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; } return new TextDecoder().decode(bytes); }

/** Bounded DALgo Database over one explicitly mapped Couchbase Data API surface. */
export class CouchbaseDataApiDatabase implements Database {
  readonly #o: Options;
  public constructor(options: CouchbaseDataApiOptions) { this.#o = resolve(options); }
  public async get<T>(key: Key, codec?: Codec<T>): Promise<RecordSnapshot<T>> { const response = await this.request("get", "GET", this.documentPath(key), undefined, [404]); if (response.status === 404) return { key, exists: false }; return this.record(key, response.value, codec, response.etag); }
  public async getMany<T>(keys: readonly Key[], codec?: Codec<T>): Promise<readonly RecordSnapshot<T>[]> { if (keys.length > this.#o.maxGetManyKeys) throw new UnsupportedError(`Couchbase getMany supports at most ${this.#o.maxGetManyKeys} keys`); const result: RecordSnapshot<T>[] = []; for (let i = 0; i < keys.length; i += this.#o.maxParallelReads) result.push(...await Promise.all(keys.slice(i, i + this.#o.maxParallelReads).map((key) => this.get(key, codec)))); return result; }
  public async insert<T>(key: Key, data: T, codec?: Codec<T>): Promise<void> { const response = await this.request("insert", "POST", this.documentPath(key), this.envelope(key, data, codec), [409]); if (response.status === 409) throw new AlreadyExistsError(key, { cause: new CouchbaseDataApiError("insert", 409) }); }
  public async set<T>(key: Key, data: T, codec?: Codec<T>): Promise<void> { await this.request("set", "PUT", this.documentPath(key), this.envelope(key, data, codec)); }
  public async setIfMatch<T>(key: Key, data: T, etag: string, codec?: Codec<T>): Promise<void> { const response = await this.request("set", "PUT", this.documentPath(key), this.envelope(key, data, codec), [409], { "if-match": this.etag(etag) }); if (response.status === 409) throw new CouchbaseCasMismatchError(); }
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  public update(key: Key, data: UpdateData): Promise<void> { return Promise.reject(new UnsupportedError("Couchbase partial updates; use a CAS-aware Data API sub-document operation explicitly")); }
  public async delete(key: Key): Promise<void> { await this.request("delete", "DELETE", this.documentPath(key), undefined, [404]); }
  public async deleteIfMatch(key: Key, etag: string): Promise<void> { const response = await this.request("delete", "DELETE", this.documentPath(key), undefined, [404, 409], { "if-match": this.etag(etag) }); if (response.status === 409) throw new CouchbaseCasMismatchError(); }
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  public runReadwriteTransaction<Result>(callback: unknown): Promise<Result> { return Promise.reject(new UnsupportedError("Couchbase Data API callback transactions")); }
  public async query<T>(query: StructuredQuery<T>): Promise<QueryPage<T>> { const source = query.source; if (source.kind !== "collection" || query.offset || query.startAt || query.startAfter || query.endAt || query.endBefore) throw new UnsupportedError("Couchbase collection-group, offset, or cursor queries"); const path = source.parent ? `${source.parent.path}/${source.name}` : source.name; const target = this.target(path); const limit = query.limit ?? this.#o.maxQueryLimit; if (!Number.isSafeInteger(limit) || limit < 1 || limit > this.#o.maxQueryLimit) throw new UnsupportedError(`Couchbase query limit must be from 1 to ${this.#o.maxQueryLimit}`); const clauses: string[] = []; const parameters: Record<string, unknown> = {}; query.filters.forEach((filter, i) => { const name = `p${i}`; jsonValue(filter.value); if (!["==", "!=", "<", "<=", ">", ">="].includes(filter.operator)) throw new UnsupportedError(`Couchbase query operator ${filter.operator}`); if (filter.field === "__name__") { keyId(filter.value); clauses.push(`d.__dalgo_id ${filter.operator === "==" ? "=" : filter.operator} $${name}`); } else { if (!/^[A-Za-z_][A-Za-z0-9_]*$/u.test(filter.field)) throw new UnsupportedError("Couchbase nested or unsafe query fields"); clauses.push(`d.data.\`${filter.field}\` ${filter.operator === "==" ? "=" : filter.operator} $${name}`); } parameters[`$${name}`] = filter.value; }); const order = query.orders.map((value) => { const direction: unknown = value.direction; if (direction !== "asc" && direction !== "desc") throw new UnsupportedError("Couchbase query order direction"); if (value.field === "__name__") return `d.__dalgo_id ${direction.toUpperCase()}`; if (!/^[A-Za-z_][A-Za-z0-9_]*$/u.test(value.field)) throw new UnsupportedError("Couchbase nested or unsafe order fields"); return `d.data.\`${value.field}\` ${direction.toUpperCase()}`; }); const statement = `SELECT d.__dalgo_id, d.data FROM \`${target.bucket}\`.\`${target.scope}\`.\`${target.collection}\` AS d${clauses.length ? ` WHERE ${clauses.join(" AND ")}` : ""}${order.length ? ` ORDER BY ${order.join(", ")}` : ""} LIMIT ${limit}`; const response = await this.request("query", "POST", "/_p/query/query/service", { statement, ...parameters }); object(response.value); if (response.value.status !== "success" || "errors" in response.value || !Array.isArray(response.value.results) || response.value.results.length > limit) throw new TypeError("malformed Couchbase SQL++ response"); return { records: response.value.results.map((value) => this.record(new Key(source.name, this.rowId(value), source.parent), value, source.codec) as ExistingRecord<T>) }; }
  private target(path: string): CouchbaseCollectionTarget { const result = typeof this.#o.collections === "function" ? this.#o.collections(path) : this.#o.collections[path]; if (!result) throw new UnsupportedError(`Couchbase collection mapping for ${path}`); return { bucket: validPart(result.bucket, "bucket"), scope: validPart(result.scope, "scope"), collection: validPart(result.collection, "collection") }; }
  private documentPath(key: Key): string { const t = this.target(key.collectionPath); return `/v1/buckets/${encodeURIComponent(t.bucket)}/scopes/${encodeURIComponent(t.scope)}/collections/${encodeURIComponent(t.collection)}/documents/${encodeURIComponent(storageKey(key.id))}`; }
  private etag(value: string): string { const result = text(value, "etag"); if (/[\r\n]/u.test(result)) throw new TypeError("etag must not contain CR or LF"); return result; }
  private envelope<T>(key: Key, data: T, codec?: Codec<T>): Envelope { keyId(key.id); const encoded = (codec ?? identityCodec as Codec<T>).encode(data); object(encoded); jsonValue(encoded); return { __dalgo_id: key.id, data: encoded }; }
  private rowId(value: unknown): string | number { object(value); keyId(value.__dalgo_id); return value.__dalgo_id; }
  private record<T>(key: Key, value: unknown, codec?: Codec<T>, etag?: string): RecordSnapshot<T> { object(value); keyId(value.__dalgo_id); if (!Object.is(value.__dalgo_id, key.id) || !("data" in value)) throw new TypeError("malformed Couchbase document envelope"); jsonValue(value.data); return { key, exists: true, data: (codec ?? identityCodec as Codec<T>).decode(value.data), metadata: etag !== undefined && /^[^\r\n]+$/u.test(etag) ? { etag } : {} }; }
  private async request(operation: string, method: string, path: string, value?: unknown, allowed: readonly number[] = [], extra: Readonly<Record<string, string>> = {}): Promise<{ status: number; value: unknown; etag?: string }> { let authorization: string; try { authorization = await this.#o.authorization(); } catch { throw new CouchbaseAuthorizationError(); } if (typeof authorization !== "string" || authorization.trim().length === 0 || /[\r\n]/u.test(authorization)) throw new CouchbaseAuthorizationError(); if (value !== undefined) jsonValue(value); const json = value === undefined ? undefined : JSON.stringify(value); if (json !== undefined && encoder.encode(json).byteLength > this.#o.maxRequestBytes) throw new RangeError("Couchbase request exceeds maxRequestBytes"); const controller = new AbortController(); const timeout = setTimeout(() => { controller.abort(); }, this.#o.timeoutMs); try { const response = await this.#o.fetch(`${this.#o.endpoint}${path}`, { method, redirect: "error", headers: { accept: "application/json", authorization, ...(json === undefined ? {} : { "content-type": "application/json" }), ...extra }, ...(json === undefined ? {} : { body: json }), signal: controller.signal }); const raw = await body(response, this.#o.maxResponseBytes); if (!response.ok && !allowed.includes(response.status)) throw new CouchbaseDataApiError(operation, response.status); let parsed: unknown = undefined; if (raw.length) { try { parsed = JSON.parse(raw); jsonValue(parsed); } catch { if (response.ok) throw new TypeError("malformed Couchbase JSON response"); } } const etag = response.headers.get("etag"); return { status: response.status, value: parsed, ...(etag === null || !/^[^\r\n]+$/u.test(etag) ? {} : { etag }) }; } finally { clearTimeout(timeout); } }
}
